// i created a new table name eventx
CREATE DATABASE user_test;
use user_test;
DROP TABLE users;
CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  phone VARCHAR(20) NOT NULL,
  refresh_token VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE eventx(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    descriptionx VARCHAR(255) NOT NULL,
    location VARCHAR(100) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE positions (
	position_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	position_code VARCHAR(100) NOT NULL,
    position_name VARCHAR(100) NOT NULL,
    id INT NOT NULL,
    FOREIGN KEY (id) REFERENCES users (id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



SELECT * FROM users;
